### ISSUE TITLE
printing html?

### ISSUE THREAD

**Issue by Jasphine** [fasteroko/StarIOPrint-cordova#5]
May I know is there a way to print it as html content? Thanks and appreciate your response.

**Comment by vkornieiev** [comment]
Hello! Thank you for you question. I have just updated plugin to support HTML text.

Example:

`cordova.plugins.starIOPrint.printHTMLText('<b>Hello World!</b>', 
    function(success) { 
        alert(success); 
    }
    , function(error) { 
        alert(error); 
    }
);`

To print simple text now you should use  

`cordova.plugins.starIOPrint.printText('Hello World!', 
    function(success) { 
        alert(success); 
    }
    , function(error) { 
        alert(error); 
    }
);`

If you have any additional propositions please respond to me.

**Comment by Jasphine** [comment]
Hi,
Thanks and appreciate for your effort and making this happen. Amazing and very useful plugin. Love it.

I have tried out and it can print HTML text now. Cool. I really appreciate and like it.

Between, this plugin support cash drawer? If yes, how ? Any references? Thanks.

Once again, thanks and appreciate your effort and help.

**Comment by vkornieiev** [comment]
Nice to hear your feedback!
Yes, it can support cashdrawer. Please open new issue with specific topic and I will help you as soon as  possible.
